// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/godofphonk/ServerEyeAPI/internal/api"
	"github.com/godofphonk/ServerEyeAPI/internal/config"
	"github.com/godofphonk/ServerEyeAPI/internal/handlers"
	"github.com/godofphonk/ServerEyeAPI/internal/services"
	"github.com/godofphonk/ServerEyeAPI/internal/storage"
	"github.com/godofphonk/ServerEyeAPI/internal/storage/interfaces"
	postgres2 "github.com/godofphonk/ServerEyeAPI/internal/storage/postgres"
	"github.com/godofphonk/ServerEyeAPI/internal/storage/repositories/postgres"
	"github.com/godofphonk/ServerEyeAPI/internal/storage/timescaledb"
	"github.com/godofphonk/ServerEyeAPI/internal/websocket"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

// InitializeApp creates a new application with all dependencies injected
func InitializeApp(cfg *config.Config) (*api.Server, error) {
	logger := NewLogger()
	server, err := api.New(cfg, logger)
	if err != nil {
		return nil, err
	}
	return server, nil
}

// wire.go:

// ProviderSet contains all the providers for dependency injection
var ProviderSet = wire.NewSet(

	NewLogger,

	NewPostgresClient,
	NewTimescaleDBClient,
	NewTimescaleDBStorageAdapter, postgres.NewGeneratedKeyRepository, postgres.NewServerRepository, services.NewServerService, services.NewMetricsService, services.NewTieredMetricsService, services.NewCommandsService, services.NewMetricsCommandsService, services.NewAuthService, websocket.NewServer, handlers.NewAuthHandler, handlers.NewHealthHandler, handlers.NewMetricsHandler, handlers.NewTieredMetricsHandler, handlers.NewServersHandler, handlers.NewServerSourcesHandler, handlers.NewCommandsHandler, api.New,
)

// NewLogger creates a new logger instance
func NewLogger() *logrus.Logger {
	logger := logrus.New()
	logger.SetLevel(logrus.InfoLevel)
	logger.SetFormatter(&logrus.JSONFormatter{
		TimestampFormat: "2006-01-02T15:04:05.000Z07:00",
	})
	return logger
}

// NewPostgresClient creates a new PostgreSQL client
func NewPostgresClient(cfg *config.Config, logger *logrus.Logger) (*postgres2.Client, error) {
	return postgres2.NewClient(cfg.DatabaseURL, logger)
}

// NewTimescaleDBClient creates a new TimescaleDB client
func NewTimescaleDBClient(cfg *config.Config, logger *logrus.Logger) (*timescaledb.Client, error) {
	if cfg.TimescaleDBURL == "" {
		return nil, fmt.Errorf("TIMESCALEDB_URL is required")
	}
	config2 := timescaledb.DefaultClientConfig()
	return timescaledb.NewClient(cfg.TimescaleDBURL, logger, config2)
}

// NewTimescaleDBStorageAdapter creates a TimescaleDB storage adapter
func NewTimescaleDBStorageAdapter(
	keyRepo interfaces.GeneratedKeyRepository,
	serverRepo interfaces.ServerRepository,
	timescaleDB *timescaledb.Client,
	logger *logrus.Logger,
	cfg *config.Config,
) *storage.TimescaleDBStorageAdapter {
	return storage.NewTimescaleDBStorageAdapter(keyRepo, serverRepo, timescaleDB, logger, cfg)
}
